#!/usr/bin/env bash
set -euo pipefail

ip="${1:-}"

if [ -z "$ip" ]; then
  echo "Usage: just install IP" >&2
  exit 2
fi

ssh -o "StrictHostKeyChecking no" "nixos@${ip}" "sudo bash -c '\
  nix-shell -p git --run \"cd /root/ && \
  if [ -d \"nix-config\" ]; then \
      rm -rf nix-config; \
  fi && \
  git clone https://github.com/ironicbadger/nix-config.git && \
  cd nix-config/lib/install && \
  sh install-nix.sh\"'"
