#!/usr/bin/env bash
set -euo pipefail

host="${1:-}"

scripts/darwin/build-system "$host"
echo "switching to new config for ${host}"
sudo "./result-darwin-${host}/sw/bin/darwin-rebuild" switch --flake ".#${host}"
