{ config, pkgs, ... }:

{
  # Studio-specific Homebrew configuration
  homebrew = {
    enable = true;
    onActivation = {
      cleanup = "zap";
      autoUpdate = true;
      upgrade = true;
    };
    
    # Homebrew casks for studio
    casks = [
      "1password-cli"
      "appcleaner"
      "betterdisplay"
      "brave-browser"
      # "cocoarestclient"
      "cursor"
      "devtoys"
      "discord"
      # "firefox"
      "font-hack-nerd-font"
      "gifcapture"
      "handbrake"
      "iina"
      # "itsycal"
      "keka"
      "localsend"
      # "monitorcontrol"
      "moom"
      # "obs"
      "ollama"
      # "only-switch"
      # "rapidapi"
      "sloth"
      "transmission"
      # "visual-studio-code"
      "vscodium"
      "xquartz"
      # "zoom"
    ];
    
    # Homebrew formulae for studio
    brews = [
      "abseil"
      "aom"
      "autoconf"
      "brotli"
      "btop"
      "c-ares"
      "ca-certificates"
      "cairo"
      "cjson"
      "cmake"
      "dav1d"
      "diffutils"
      "expat"
      "ffmpeg"
      "fish"
      "flac"
      "fontconfig"
      "freerdp"
      "freetype"
      "frei0r"
      "fribidi"
      "fx"
      "fzf"
      "gettext"
      "gh"
      "giflib"
      "gitui"
      "glib"
      "gmp"
      "gnu-getopt"
      "gnupg"
      "gnutls"
      "graphite2"
      "harfbuzz"
      "highway"
      "hugo"
      "icu4c@76"
      "icu4c@77"
      "imagemagick"
      "imath"
      "jasper"
      "jpeg-turbo"
      "jpeg-xl"
      "jq"
      "lame"
      "lazygit"
      "leptonica"
      "lf"
      "libarchive"
      "libass"
      "libassuan"
      "libb2"
      "libbluray"
      "libde265"
      "libdeflate"
      "libevent"
      "libgcrypt"
      "libgit2"
      "libgpg-error"
      "libheif"
      "libidn2"
      "libksba"
      "liblinear"
      "liblqr"
      "libmicrohttpd"
      "libnghttp2"
      "libogg"
      "libomp"
      "libpng"
      "libraw"
      "librist"
      "libsamplerate"
      "libsndfile"
      "libsodium"
      "libsoxr"
      "libssh"
      "libssh2"
      "libtasn1"
      "libtiff"
      "libtool"
      "libunibreak"
      "libunistring"
      "libusb"
      "libuv"
      "libvidstab"
      "libvmaf"
      "libvorbis"
      "libvpx"
      "libvterm"
      "libx11"
      "libxau"
      "libxcb"
      "libxcursor"
      "libxdmcp"
      "libxext"
      "libxfixes"
      "libxi"
      "libxinerama"
      "libxrandr"
      "libxrender"
      "libxv"
      "libzip"
      "libyaml"
      "little-cms2"
      "llvm@19"
      "lpeg"
      "lua"
      "luajit"
      "luv"
      "lz4"
      "lzo"
      "m4"
      "mad"
      "mas"
      "mbedtls"
      "midnight-commander"
      "mpdecimal"
      "mpg123"
      "msgpack"
      "ncdu"
      "ncurses"
      "neofetch"
      "neovim"
      "nettle"
      "nmap"
      "node"
      "npth"
      "oniguruma"
      "opencore-amr"
      "openexr"
      "openjdk"
      "openjpeg"
      "openssl@3"
      "opus"
      "opusfile"
      "otree"
      "p11-kit"
      "pango"
      "pass"
      "pcre2"
      "pinentry"
      "pixman"
      "pkcs11-helper"
      "pkgconf"
      "protobuf"
      "pwgen"
      "pyenv"
      "python-packaging"
      "python@3.12"
      "python@3.13"
      "qrencode"
      "rav1e"
      "rbenv"
      "readline"
      "rename"
      "ripgrep"
      "rubberband"
      "ruby"
      "ruby-build"
      "rust"
      "s-lang"
      "screenresolution"
      "sdl2"
      "sdl3"
      "sdl3_ttf"
      "shared-mime-info"
      "sk"
      "snappy"
      "sox"
      "speedtest-cli"
      "speex"
      "sqlite"
      "srt"
      "svt-av1"
      "tesseract"
      "thefuck"
      "theora"
      "tldr"
      "tmux"
      "tree"
      "tree-sitter"
      "unbound"
      "unibilium"
      "utf8proc"
      "webp"
      "wget"
      "x264"
      "x265"
      "xorgproto"
      "xvid"
      "xz"
      "yq"
      "zeromq"
      "zimg"
      "zlib"
      "zsh-completions"
      "zstd"
    ];
    
    # Mac App Store applications for studio
    masApps = {
      "1Password for Safari" = 1569813296;
      "C2 Password for Safari" = 1566336292;
      "Developer" = 640199958;
      "Due" = 524373870;
      "Eagle for Safari" = 1526651672;
      "Folder Preview" = 6698876601;
      "GarageBand" = 682658836;
      "Gifski" = 1351639930;
      "GreenBooks" = 407094598;
      "Hidden Bar" = 1452453066;
      "Hush" = 1544743900;
      "Keepforest File Manager" = 1491186567;
      "Keynote" = 409183694;
      "Noir" = 1592917505;
      "Numbers" = 409203825;
      "Pages" = 409201541;
      "Patterns" = 429449079;
      "Perplexity" = 6714467650;
      "Photomator" = 1444636541;
      "Speediness" = 1596706466;
      "SponsorBlock" = 1573461917;
      "Tab Space" = 1473726602;
      "Tempomate" = 1157672888;
      "Trello" = 1278508951;
      "Xcode" = 497799835; # Can we have Xcode on a external drive?
      "Yubico Authenticator" = 1497506650;
    };
  };
}
